// pages/post/[slug].jsx
import fs from 'fs';
import matter from 'gray-matter';
import Giscus from '@giscus/react';
import SlugToDate from '../../components/SlugToDate';
import TagsList from '../../components/Tags';
import { md, replaceJekyllLinks, replaceMath } from '../../components/markdownHelpers';

export async function getStaticPaths() {
    const files = fs.readdirSync('posts');
    const paths = files.map((fileName) => ({
        params: {
            slug: fileName.replace('.md', ''),
        },
    }));
    return {
        paths,
        fallback: false,
    };
}

export async function getStaticProps({ params: { slug } }) {
    const fileName = fs.readFileSync(`posts/${slug}.md`, 'utf-8');
    const { data: frontmatter, content } = matter(fileName);
    return {
        props: {
            slug,
            frontmatter,
            content,
        },
    };
}

function Information({keyStr, valueStr}) {
    return (
        <div className='flex space-x-4 mt-2'>
            <div className='text-gray-400'>{keyStr}:</div>
            <div className='prose-p:m-0'>{valueStr}</div>
        </div>
    );
}


function PublicationPage({ frontmatter, content }) {
    return (
        <div className='prose dark:prose-invert text-justify mx-auto max-w-screen-xl prose-img:block prose-img:m-auto prose-img:max-h-96 prose-p:w-full '>
            <h1>{frontmatter.title}</h1>
            <Information keyStr="Type" valueStr={frontmatter.type} />
            <Information
                keyStr="Authors"
                valueStr={(<div dangerouslySetInnerHTML={{ __html: md.render(frontmatter.authors) }} />)} />
            <Information keyStr="Venue" valueStr={frontmatter.venue} />
            <Information keyStr="Date of publication" valueStr={<SlugToDate slug={frontmatter.date} />} />
            <Information keyStr="URL" valueStr={(<a href={frontmatter.paperurl}>{frontmatter.doi}</a>)} />
            <Information
                keyStr="Abstract"
                valueStr={(<div dangerouslySetInnerHTML={{ __html: replaceMath(replaceJekyllLinks(md.render(frontmatter.abstract))) }} />)} />

            <Information
                keyStr="Citation"
                valueStr={(<div dangerouslySetInnerHTML={{ __html: replaceMath(md.render(frontmatter.citation)) }} />)} />

            <div class="m-4 w-full border-t-4 border-slate-400/25" />

            <div dangerouslySetInnerHTML={{ __html: replaceMath(replaceJekyllLinks(md.render(content))) }} />

            <div class="m-4 w-full border-t-4 border-slate-400/25" />

            <Giscus
                id="comments"
                repo="ahmed-shariff/ahmed-shariff.github.io"
                repoId="MDEwOlJlcG9zaXRvcnkxMjU3MDU3Nzc="
                category="Announcements"
                categoryId="DIC_kwDOB34eMc4COpxh"
                mapping="pathname"
                reactionsEnabled="1"
                emitMetadata="0"
                inputPosition="top"
                theme="light"
                lang="en"
                loading="lazy"
                crossorigin="anonymous"
            />
        </div >
    );
}


function PostPage({ slug, frontmatter, content }) {
    return (
        <div className='prose dark:prose-invert text-justify mx-auto max-w-screen-xl prose-img:block prose-img:m-auto prose-img:max-h-96 prose-p:w-full'>
            <div className='text-xs text-slate-400'>
                <SlugToDate slug={slug} />
                <TagsList tags={frontmatter.tags} link />
            </div>
            <h1>{frontmatter.title}</h1>
            <div dangerouslySetInnerHTML={{ __html: replaceMath(replaceJekyllLinks(md.render(content))) }} />

            <div class="m-4 w-full border-t-4 border-slate-400/25" />

            <Giscus
                id="comments"
                repo="ahmed-shariff/ahmed-shariff.github.io"
                repoId="MDEwOlJlcG9zaXRvcnkxMjU3MDU3Nzc="
                category="Announcements"
                categoryId="DIC_kwDOB34eMc4COpxh"
                mapping="pathname"
                reactionsEnabled="1"
                emitMetadata="0"
                inputPosition="top"
                theme="light"
                lang="en"
                loading="lazy"
                crossorigin="anonymous"
            />
        </div>
    );
}

export default function Page({slug, frontmatter, content}) {
    if ("doi" in frontmatter) {
        return (<PublicationPage frontmatter={frontmatter} content={content} />);
    } else {
        return (<PostPage slug={slug} frontmatter={frontmatter} content={content} />);
    }
}

// src/routes/post/[slug]/+page.svelte
<script>
 import Information from "$lib/Information.svelte";
 import Tag from "$lib/Tag.svelte";
 import Giscus from '@giscus/svelte';
 import FilePdf from "$lib/icons/FilePDF.svelte";

 export let data;
</script>

<article class="p-5 md:p-0 prose dark:prose-invert mx-auto max-w-screen-xl prose-img:block prose-img:m-auto prose-img:max-h-96 prose-p:w-full prose-h1:text-left break-words prose-table:table-auto prose-table:bg-slate-900 prose-td:border prose-td:border-slate-600 prose-td:p-2">

    <div class='text-xs text-slate-400'>
        {data.date}
        {#if (data.meta.tags !== undefined) && (data.meta.tags !== null)}
            <div class="flex flex-row space-x-3">
            {#each data.meta.tags as tag}
                <Tag {tag} inverseOp={true} />
            {/each}
            </div>
        {/if}
    </div>
    <h1>
        {#if data.published}
            [DRAFT]
        {/if}
        {data.title}
    </h1>

    {#if data.meta.doi !== undefined}
        <Information keyStr="Type" valueStr={data.meta.type} />
        <Information
            keyStr="Authors"
            valueStr={data.meta.authors} />
        <Information keyStr="Venue">{data.meta.venue}</Information>
        <Information keyStr="Date of publication">{data.date}</Information>
        <Information keyStr="URL"><a href={data.meta.paperurl.trimEnd().trimStart()}>{data.meta.doi}</a></Information>
        <Information keyStr="pdf download"><a href={data.meta.pdf.trimEnd().trimStart()} class=""><FilePdf /></a></Information>
        <Information keyStr="Abstract" inCols={true}>{data.meta.abstract}</Information>
        <Information keyStr="Citation" inCols={true}>{data.meta.citation}</Information>
    {/if}

    <svelte:component this={data.content} />

    <Giscus
        id="comments"
        repo="ahmed-shariff/ahmed-shariff.github.io"
        repoId="MDEwOlJlcG9zaXRvcnkxMjU3MDU3Nzc="
        category="Announcements"
        categoryId="DIC_kwDOB34eMc4COpxh"
        mapping="pathname"
        reactionsEnabled="1"
        emitMetadata="0"
        inputPosition="top"
        theme="light"
        lang="en"
        loading="lazy"
        crossorigin="anonymous"
    />
</article>
